### ISSUE TITLE
Provide some tips on how to get access to the data from web apps

### ISSUE THREAD

**Issue by frol** [near/near-indexer-for-explorer#123]
# Story

It will be useful for those who are not very familiar with the backends / databases to be able to get access to the data right from the web apps. 

That would be a stretch if we extend our shared public access to that, but we may at least document and recommend people using it.

# Solutions

There are a few solutions that can turn PostgreSQL database into API:

* [PostgREST](https://postgrest.org/)
* [Hasura](https://github.com/hasura/graphql-engine)

## PostgREST

I played around with PostgREST, and it is as simple as running this Docker Compose file:

```yaml
version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://public_readonly:nearprotocol@104.199.89.51/mainnet_explorer
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: public_readonly
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000"
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
```

This uses the shared access credentials to the database, and you get http://127.0.0.1:3000 REST API server along with http://127.0.0.1:8080 Swagger UI to play with the APIs interactively:

![image](https://user-images.githubusercontent.com/304265/121396112-6b8a4d00-c929-11eb-88f6-b0f095b62193.png)

(you cannot really insert, update, or delete from Indexer for Explorer database using read-only access, but PostgREST does not realize that for some reason and still generates unnecessary endpoints)

Just as an example, here is the type of query you can run:

![image](https://user-images.githubusercontent.com/304265/121396334-a68c8080-c929-11eb-981c-d75a68752ea0.png)

(there are some custom query selectors that you can use and that will be translated into SQL)

There are also instructions on how to run it on Heroku: https://postgrest.org/en/stable/install.html#deploying-to-heroku

## Hasura

I have not tried it yet, but I assume it is a similar experience with GraphQL and OpenAPI support.
